from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

from src.models.SPDAttention import spd_log

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.datasets.PhysioNetMI_preprocess import preprocess_spd


DEFAULT_FILTER_BANK = (
    (8.0, 12.0),
    (12.0, 16.0),
    (16.0, 20.0),
    (20.0, 24.0),
    (24.0, 28.0),
    (28.0, 32.0),
)


def parse_filter_bank(raw: str) -> list[tuple[float, float]]:
    bands = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        low_raw, high_raw = part.split("-", 1)
        bands.append((float(low_raw), float(high_raw)))
    if not bands:
        raise argparse.ArgumentTypeError("filter bank cannot be empty")
    return bands


def parse_subjects(raw: str | None) -> list[int] | None:
    if raw is None or raw.strip() == "":
        return None
    subjects = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            start_raw, end_raw = part.split("-", 1)
            subjects.extend(range(int(start_raw), int(end_raw) + 1))
        else:
            subjects.append(int(part))
    return sorted(set(subjects))


def print_array_stats(name: str, x: np.ndarray) -> None:
    finite = np.isfinite(x)
    print(f"\n{name}")
    print("shape:", x.shape)
    print("dtype:", x.dtype)
    print("has_nan:", np.isnan(x).any())
    print("has_inf:", np.isinf(x).any())
    print("finite_ratio:", finite.mean())
    if finite.any():
        finite_x = x[finite]
        print("min:", finite_x.min())
        print("max:", finite_x.max())
        print("mean:", finite_x.mean())
        print("std:", finite_x.std())
        print("p01:", np.percentile(finite_x, 1))
        print("p50:", np.percentile(finite_x, 50))
        print("p99:", np.percentile(finite_x, 99))


def print_spd_eigen_stats(x_spd: np.ndarray, eps: float) -> None:
    x_sym = 0.5 * (x_spd + np.swapaxes(x_spd, -1, -2))
    eigvals = np.linalg.eigvalsh(x_sym)
    min_eig = eigvals[..., 0]
    max_eig = eigvals[..., -1]
    cond = max_eig / np.maximum(min_eig, eps)

    print_array_stats("eigenvalues/all", eigvals)
    print_array_stats("eigenvalues/min_per_matrix", min_eig)
    print_array_stats("eigenvalues/max_per_matrix", max_eig)
    print_array_stats("condition_number", cond)

    print("\nSPD validity summary")
    print("num_matrices:", int(np.prod(x_spd.shape[:-2])))
    print("num_min_eig_below_0:", int((min_eig < 0).sum()))
    print(f"num_min_eig_below_eps({eps:g}):", int((min_eig < eps).sum()))
    print("worst_min_eig:", float(min_eig.min()))
    print("worst_condition_number:", float(cond.max()))


def print_per_band_segment_stats(x_spd: np.ndarray, filter_bank: list[tuple[float, float]]) -> None:
    # Expected shape: (n_trials, segment, frequency, n_channels, n_channels)
    if x_spd.ndim != 5:
        print(f"\nSkip per-band/segment stats: expected 5D SPD array, got {x_spd.ndim}D.")
        return

    _, n_segments, n_bands = x_spd.shape[:3]
    print("\nPer frequency band value range")
    for band_index in range(n_bands):
        band_name = (
            f"{filter_bank[band_index][0]:g}-{filter_bank[band_index][1]:g} Hz"
            if band_index < len(filter_bank)
            else f"band_{band_index}"
        )
        print_array_stats(f"band/{band_name}", x_spd[:, :, band_index])

    print("\nPer temporal segment value range")
    for segment_index in range(n_segments):
        print_array_stats(f"segment/{segment_index}", x_spd[:, segment_index])


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Inspect numerical range of SPD matrices generated by preprocess_spd()."
    )
    parser.add_argument(
        "--root-dir",
        default="data/MNE-eegbci-data/files/eegmmidb/1.0.0",
    )
    parser.add_argument(
        "--subjects",
        default="1",
        help="Subjects to load, e.g. 1, 1-5, or empty string for all subjects. Default: 1",
    )
    parser.add_argument(
        "--channels",
        default="FC5, FC3, FC1, FCz, FC2, FC4, FC6, C5, C3, C1, Cz, C2, C4, C6, CP5, CP3, CP1, CPz, CP2, CP4, CP6",
        help="Optional comma-separated channels, e.g. C3,Cz,C4.",
    )
    parser.add_argument(
        "--filter-bank",
        type=parse_filter_bank,
        default=list(DEFAULT_FILTER_BANK),
        help="Comma-separated bands, e.g. 8-12,12-16,16-20.",
    )
    parser.add_argument("--estimator", default="lwf")
    parser.add_argument("--eps", type=float, default=1e-6)
    parser.add_argument("--sfreq", type=float, default=160.0)
    parser.add_argument("--segment-duration", type=float, default=1.0)
    parser.add_argument("--stride-duration", type=float, default=0.5)
    parser.add_argument("--imaged", action="store_true", default=True)
    parser.add_argument("--executed", action="store_true", default=False)
    parser.add_argument("--task-types", default="unilateral_fist,both")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    task_types = tuple(part.strip() for part in args.task_types.split(",") if part.strip())

    x, y, class_names = preprocess_spd(
        filter_bank=args.filter_bank,
        root_dir=args.root_dir,
        subjects=parse_subjects(args.subjects),
        channels=args.channels,
        estimator=args.estimator,
        eps=args.eps,
        sfreq=args.sfreq,
        segment_duration=args.segment_duration,
        stride_duration=args.stride_duration,
        imaged=args.imaged,
        executed=args.executed,
        task_types=task_types,
    )

    print("\nLabels")
    print("y shape:", y.shape)
    print("class_names:", class_names)
    print("class_counts:", {name: int((y == idx).sum()) for idx, name in enumerate(class_names)})

    print_array_stats("X_spd/all_values", x)
    print_per_band_segment_stats(x, args.filter_bank)
    print_spd_eigen_stats(x, eps=args.eps)

    log_v = spd_log(x)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
