defaults:
  download_dir: data
datasets:
  - name: PhysionetMI
    # Exclude S088, S089, S092, S100, S104, and S106.
    subjects: 1-87,90-91,93-99,101-103,105,107-109
    params:
      imagined: true
      executed: false
    sample_rate: 160
